---
title: "Reading data from the web"
output: github_document
date: "2024-10-12"
---

```{r setup, include=FALSE}
library(tidyverse)
library(rvest)
library(httr)
```

## Scrape a table 

I want the first table from [this page] (https://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm)

read in the html 

```{r}
url = "https://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm"

drug_use_html = read_html(url)
```

extract the table(s); focus on the first one

```{r}
table_marj = 
drug_use_html |>
  html_table() |>
  first() |>
  slice(-1) |>
  as_tibble()
```

## Star Wars Movie info 

I want the data from [here] (https://www.imdb.com/list/ls070150896/)

```{r}
url = "https://www.imdb.com/list/ls070150896/"

swm_html = read_html(url)
```

Grab elements that I want. 

```{r}
titles_vec = 
  swm_html |>
  html_nodes(css = ".lister-item-header a") |>
  html_text()

metascore_vec = 
  swm_html |>
  html_elements(".metacritic-score-box") |>
  html_text()

runtime_vec = 
  swm_html |>
  html_elements(".dli-title-metadata-item:nth-child(2)") |>
  html_text()

swm_df = 
  tibble(
    title = titles_vec, 
    runtime = runtime_vec)
```

## Get some water data 

This is coming from an API 

```{r}
nyc_water = 
  GET("https://data.cityofnewyork.us/resource/ia2d-e54m.csv") %% 
  content("text")
```

Let's get Pokemon API 

```{r}
poke = 
  GET("http://pokeapi.co/api/v2/pokemon/1") %% 
  content()
```

